"""Write launcher root env_config.py from deploy_environment results."""

from __future__ import annotations

import secrets
from pathlib import Path
from typing import Any, Mapping


def write_env_config_py(
    launcher_root: Path,
    env_name: str,
    aws_region: str,
    cognito: Mapping[str, Any],
    s3_bucket_name: str,
    websocket_connections: str = "",
    vite_websocket_url: str = "",
    websocket_connections_staging: str = "",
    vite_websocket_url_staging: str = "",
) -> Path:
    """Create or overwrite env_config.py at launcher repo root."""
    csrf = secrets.token_urlsafe(48)
    secret = secrets.token_urlsafe(48)

    lines = [
        '"""Auto-generated by deploy_environment.py. Copy into the system app or adjust import paths."""',
        "",
        f"DYNAMODB_ENTITY_TABLE = {repr(f'{env_name}_entities')}",
        f"DYNAMODB_BLUEPRINT_TABLE = {repr(f'{env_name}_blueprints')}",
        f"DYNAMODB_RINGDATA_TABLE = {repr(f'{env_name}_data')}",
        f"DYNAMODB_REL_TABLE = {repr(f'{env_name}_rel')}",
        f"DYNAMODB_CHAT_TABLE = {repr(f'{env_name}_chat')}",
        "",
        f"CSRF_SESSION_KEY = {repr(csrf)}",
        f"SECRET_KEY = {repr(secret)}",
        "",
        f"COGNITO_REGION = {repr(aws_region)}",
        f"COGNITO_USERPOOL_ID = {repr(str(cognito['user_pool_id']))}",
        f"COGNITO_APP_CLIENT_ID = {repr(str(cognito['app_client_id']))}",
        "",
        f"S3_BUCKET_NAME = {repr(s3_bucket_name)}",
        "",
        f"WEBSOCKET_CONNECTIONS = {repr(websocket_connections)}",
        f"VITE_WEBSOCKET_URL = {repr(vite_websocket_url)}",
        f"WEBSOCKET_CONNECTIONS_STAGING = {repr(websocket_connections_staging)}",
        f"VITE_WEBSOCKET_URL_STAGING = {repr(vite_websocket_url_staging)}",
        "",
        "# OpenSearch (uncomment when OpenSearch is enabled in deploy_environment.py)",
        "# OPENSEARCH_ENDPOINT = 'https://search-xxx.us-east-1.es.amazonaws.com'",
        f"# OPENSEARCH_INDEX = {repr(f'{env_name}-documents')}",
        "",
    ]
    path = launcher_root / "env_config.py"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
